---
- include_tasks: install_osx.yml
  when: ansible_distribution == "MacOSX"

- include_tasks: install_linux.yml
  when: ansible_distribution != "MacOSX"

- name: Install testrpm and truffle
  npm: name="{{item}}" global=yes
  become: true
  with_items:
    - ethereumjs-testrpc
    - truffle
